#!/bin/sh

if ! [ -d "./env" ]
then
  echo "You are missing a virtual Environment"
  echo "run the following commands:"
  echo "python3 -m venv env"
  echo ". ./env/bin/activate"
  exit
fi

if [[ "$VIRTUAL_ENV" != "" ]]
then
  pip3 install -r requirements.txt
else
  echo "CAREFUL YOU ARE NOT IN YOUR VIRTUAL ENV"
  echo "To enter your virtual env use the following command"
  echo ". ./env/bin/activate"
fi



